name: pyscore
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
   sdk: ^3.5.3

dependencies:
   flutter:
      sdk: flutter
   cupertino_icons: ^1.0.8
   google_fonts: ^6.2.1
   carousel_slider: ^5.0.0
   smooth_page_indicator: ^1.2.0+3
   provider: ^6.1.2
   intl: ^0.19.0
   sqflite: ^2.2.6
   sqflite_common_ffi: ^2.3.4+3
   sqlite3_flutter_libs: ^0.5.28
   path: ^1.8.3
   path_provider: ^2.0.14
   uuid: ^4.5.1
   fluttertoast: ^8.2.8
   flutter_code_editor: ^0.3.2
   highlight: ^0.7.0
   file_picker: ^8.1.7
   crypt: ^4.3.1
   recase: ^4.1.0
   random_string_generator: ^2.0.0
   flutter_quill: ^10.8.5
   flutter_quill_extensions: ^10.8.5
   pretty_json: ^2.0.0
   desktop_drop: ^0.5.0
   cross_file: ^0.3.4+2
   window_manager: ^0.4.3
   flython:
      git: https://github.com/jPael/flython.git
   flutter_localizations:
      sdk: flutter
   mini_server: ^1.1.0
   http: ^1.2.2

dev_dependencies:
   flutter_test:
      sdk: flutter

   flutter_lints: ^4.0.0

flutter:
   uses-material-design: true

   # To add assets to your application, add an assets section, like this:
   assets:
      - assets\icons\operator.png
      - assets\icons\python.png
      - assets\icons\search.png
      - assets\images\loginDesign.jpg
      - assets\images\binary.jpg
      - assets\icons\password.png
      - assets\icons\user.jpeg
      - assets\gif\try.gif
      - assets\gif\try1.gif
      - assets\gif\try2.gif

   # An image asset can refer to one or more resolution-specific "variants", see
   # https://flutter.dev/to/resolution-aware-images

   # For details regarding adding assets from package dependencies, see
   # https://flutter.dev/to/asset-from-package

   # To add custom fonts to your application, add a fonts section here,
   # in this "flutter" section. Each entry in this list should have a
   # "family" key with the font family name, and a "fonts" key with a
   # list giving the asset and other descriptors for the font. For
   # example:
   # fonts:
   #   - family: Schyler
   #     fonts:
   #       - asset: fonts/Schyler-Regular.ttf
   #       - asset: fonts/Schyler-Italic.ttf
   #         style: italic
   #   - family: Trajan Pro
   #     fonts:
   #       - asset: fonts/TrajanPro.ttf
   #       - asset: fonts/TrajanPro_Bold.ttf
   #         weight: 700
   #
   # For details regarding fonts from package dependencies,
   # see https://flutter.dev/to/font-from-package
